//
// PDSUI_ModuleOne_Ex2
// ContentView.swift
//
// Created on 11/30/24
// Swift Version 6.0
//
// ATS Project - Assisted by Claude
// Kodeco Tutorial
// Understanding Data Flow in SwiftUI
// Module 1 - Exercise 2

//import SwiftUI

// Stock code autogenerated by Xcode
//struct ContentView: View {
//    var body: some View {
//        VStack {
//            Image(systemName: "globe")
//                .imageScale(.large)
//                .foregroundStyle(.tint)
//            Text("Hello, world!")
//        }
//        .padding()
//    }
//}

//Kodeco tutorial code
//struct ContentView: View {
//  let entries: [FinancialEntry]
//
//  var body: some View {
//     NavigationView {
//      List {
//        Section(header: Text("Entries")) {
//          ForEach(entries) { entry in
//            FinancialEntryRow(entry: entry)
//          }
//        }
//      }
//      .navigationTitle("Budget Tracker")
//    }
//  }
// }
//
//
//// Stock code autogenerated by Xcode
////#Preview {
////    ContentView()
////}
//
//
//#Preview {
//    ContentView(entries: entries)
//}

// Refactored by Claude
import SwiftUI

struct ContentView: View {
  let entries: [FinancialEntry]

  var body: some View {
     NavigationView {
      List {
        Section(header: Text("Entries")) {
          ForEach(entries) { entry in
            FinancialEntryRow(entry: entry)
          }
        }
      }
      .navigationTitle("Budget Tracker")
    }
  }
}

#Preview {
    // Create sample entries for the preview
    let sampleEntries = [
        FinancialEntry(amount: 3000, category: "Income", isExpense: false),
        FinancialEntry(amount: 120, category: "Groceries", isExpense: true)
    ]
    return ContentView(entries: sampleEntries)
}
