//
// PDSUI_ModuleOne_Ex2
// PDSUI_ModuleOne_Ex2App.swift
//
// Created on 11/30/24
// Swift Version 6.0
//
// ATS Project - Assisted by Claude
// Kodeco Tutorial
// Understanding Data Flow in SwiftUI
// Module 1 - Exercise 2

// Stock code autogenerated by Xcode

//import SwiftUI

//@main
//struct PDSUI_ModuleOne_Ex2App: App {
//    var body: some Scene {
//        WindowGroup {
//            ContentView()
//        }
//    }
//}


// Kodeco tutorial code - modified

//// MARK - Model
//struct FinancialEntry: Identifiable {
//    let id = UUID()
//    var amount: Double
//    var category: String
//    let isExpense: Bool
//}
//
//// MARK - App & View Hierarchy
//@main
//struct PDSUI_ModuleOne_Ex2App: App {
//  let entries = [
//    FinancialEntry(
//      id: UUID(),
//      amount: 3000,
//      category: "Income",
//      isExpense: false
//    ),
//    FinancialEntry(
//      id: UUID(),
//      amount: 120,
//      category: "Groceries",
//      isExpense: true
//    ),
//    FinancialEntry(
//      id: UUID(),
//      amount: 500,
//      category: "Technology",
//      isExpense: true
//    ),
//    FinancialEntry(
//      id: UUID(),
//      amount: 10,
//      category: "Subscription",
//      isExpense: true
//    )
//  ]
//
//  var body: some Scene {
//    WindowGroup {
//      ContentView(entries: entries)
//    }
//  }
//}
//
//struct FinancialEntryRow: View {
//  let entry: FinancialEntry
//
//  var body: some View {
//    HStack {
//      Text(entry.isExpense ? "Expense" : "Income")
//      Spacer()
//      Text("$\(entry.amount, specifier: "%.2f")")
//        .foregroundColor(
//          entry.isExpense ? .red : .green
//         )
//     }
//  }
// }

// Refactored by Claude
import SwiftUI

// MARK: - Model
struct FinancialEntry: Identifiable {
    let id = UUID()
    var amount: Double
    var category: String
    let isExpense: Bool
}

// MARK: - Views
struct FinancialEntryRow: View {
  let entry: FinancialEntry

  var body: some View {
    HStack {
      Text(entry.isExpense ? "Expense" : "Income")
      Spacer()
      Text("$\(entry.amount, specifier: "%.2f")")
        .foregroundColor(
          entry.isExpense ? .red : .green
         )
     }
  }
}

// MARK: - App
@main
struct PDSUI_ModuleOne_Ex2App: App {
  let entries = [
    FinancialEntry(
      amount: 3000,
      category: "Income",
      isExpense: false
    ),
    FinancialEntry(
      amount: 120,
      category: "Groceries",
      isExpense: true
    ),
    FinancialEntry(
      amount: 500,
      category: "Technology",
      isExpense: true
    ),
    FinancialEntry(
      amount: 10,
      category: "Subscription",
      isExpense: true
    )
  ]

  var body: some Scene {
    WindowGroup {
      ContentView(entries: entries)
    }
  }
}
