//
// PDSUI_ModuleOne_Ex1
// ContentView.swift
//
// Created on 11/30/24
// Swift Version 6.0
//
// ATS Project - Assisted by Claude
// Kodeco Tutorial
// Understanding Data Flow in SwiftUI
// Module 1

import SwiftUI

// Stock code autogenerated by Xcode
//struct ContentView: View {
//    var body: some View {
//        VStack {
//            Image(systemName: "globe")
//                .imageScale(.large)
//                .foregroundStyle(.tint)
//            Text("Hello, world!")
//        }
//        .padding()
//    }
//}

// Kodeco tutorial code
struct Person {
  let name: String
  let age: Int
}

struct ContentView: View {
    let person: Person

    var body: some View {
        VStack {
            Text("Name: \(person.name)")
            Text("Age: \(person.age)")
        }
    }
}


// Stock code autogenerated by Xcode
//#Preview {
//    ContentView()
//}

// Modified code to run the tutorial
#Preview {
    // Code suggested by Claude
    ContentView(person: Person(name: "Preview Person", age: 25))
}
