//
// PDSUI_ModuleOne_Ex1
// PDSUI_ModuleOne_Ex1App.swift
//
// Created on 11/30/24
// Swift Version 6.0
//
// ATS Project - Assisted by Claude
// Kodeco Tutorial
// Understanding Data Flow in SwiftUI
// Module 1 - Exercise 1

import SwiftUI

// Stock code autogenerated by Xcode

//@main
//struct PDSUI_ModuleOne_Ex1App: App {
//    var body: some Scene {
//        WindowGroup {
//            ContentView()
//        }
//    }
//}


// Kodeco tutorial code
@main
struct MyApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView(person: Person(name: "Alice", age: 30))
        }
    }
}
